data <- read.csv("cloth.csv")
View(data)
A<- c(data$Size)
Mean = mean(A)
Min = min(data$Size)
Max = max(data$Size)
Minmax = (A-Min)/(Max-Min)
deciN = (A/100)
print(Mean)
print(Min)
print(Max)
print(Minmax)
print(deciN)